version: "3.3"
services:
    gateway:
        image: ${REGISTRY}/qfind-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - api

    frontend:
        image: ${REGISTRY}/qfind-frontend:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/qfind-api:${IMAGE_TAG}
        restart: always
        depends_on:
            - api-php-fpm

    api-php-fpm:
        image: ${REGISTRY}/qfind-api-php-fpm:${IMAGE_TAG}
        restart: always
